name: First pipeline

on:
  push:
    branches:
      - main

jobs:
      Example_Jobs:
         runs-on: ubuntu-latest

         steps:
           - name: print message 
             run: echo "welcome mahmoud selim!"

           - name: Check repository
             uses: actions/checkout@v6.0.2

           - name: list repository files
             run: ls -la
           